[versions]
agp = "9.4.0"
core-ktx = "1.19.0"
appcompat = "1.8.0"
material = "1.14.0"
constraintlayout = "2.2.2"
maplibre = "13.6.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
maplibre-android-sdk = { group = "org.maplibre.gl", name = "android-sdk", version.ref = "maplibre" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
